class GenerateWord {
  constructor() {
    this.word =
      "This will be replaced with word when you press the Begin button";
    this.words = [
      "alsoon",
      "alsoone",
      "alstroemeria",
      "alstroemerias",
      "alt",
      "altaltissimo",
      "altaltissimos",
      "altar",
      "altarage",
      "altarages",
      "altarpiece",
      "altarpieces",
      "altars",
      "altarwise",
      "altazimuth",
      "altazimuths",
      "horologia",
      "horologic",
      "horological",
      "horologies",
      "horologion",
      "horologions",
      "horologist",
      "horologists",
      "horologium",
      "horologiums",
      "horology",
      "horometrical",
      "horometries",
      "horometry",
      "paranymphs",
      "paranyms",
      "parapara",
      "paraparas",
      "parapareses",
      "paraparesis",
      "paraparetic",
      "parapente",
      "parapentes",
      "parapenting",
      "parapentings",
      "paraperiodic",
      "parapet",
      "parapeted",
      "saponifiers",
      "saponifies",
      "saponify",
      "saponifying",
      "saponin",
      "saponine",
      "saponines",
      "saponins",
      "saponite",
      "saponites",
      "sapor",
      "zonulas",
      "zonule",
      "zonules",
      "zonulet",
      "zonulets",
      "zonure",
      "zonures",
      "zoo",
      "zoobiotic",
      "zooblast",
      "zooblasts",
      "zoocephalic",
      "zoochemical",
      "zoochemistries",
      "zoochemistry",
      "saturnalia",
      "saturnalian",
      "saturnalianly",
      "saturnalias",
      "saturnic",
      "saturniid",
      "saturniids",
      "saturnine",
      "saturninely",
      "saturninities",
      "saturninity",
      "saturnism",
      "saturnisms",
      "saturnist",
      "saturnists",
      "satyagraha",
      "satyagrahas",
      "satyagrahi",
      "satyagrahis",
      "satyr",
      "satyra",
      "satyral",
      "satyrals",
      "satyras",
      "satyresque",
      "satyress",
      "satyresses",
      "satyriases",
      "revisory",
      "revisualisation",
      "revisualization",
      "revisualizations",
      "revitalisation",
      "revitalisations",
      "revitalise",
      "revitalised",
      "revitalises",
      "revitalising",
      "revitalization"
    ];

    this.randomize();
  }

  randomize() {
    this.word = this.words[Math.floor(Math.random() * this.words.length)];
    return this.word;
  }
}

const Word = new GenerateWord();

export { Word };
